### ISSUE TITLE
Support Mensa Card TU Chemnitz 

### ISSUE THREAD

**Issue by danielpusicha** [TheJKM/MensaGuthaben-iOS#5]
> If you want to add a new card of an unsupported university / canteen, please open an issue. I plan to add a feature to scan such cards, so we can easily find the required data.

I would love if you could add support for the Mensa card at TU Chemnitz

**Comment by TheJKM** [comment]
Hi, thank you for your interest in my app and please excuse the late reply. I know that I planned to build such a feature, but in the meantime, I got to analyze several unsupported cards, and every single of them did not store the amount locally on the card, which is a hard requirement for my app to work. This let me abandon my plans for this feature. So, unfortunately, if the card does not work my app won't help.
In case you have other options to analyze the card (there are several Android apps able to dump these cards) and find the amount storage position, I'll add support for this type of card.
